// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAjRW7nwHrTWGMipxWecjjNoeotUjayaE',
    appId: '1:878165496369:web:07e8dacb77eab44fa93b10',
    messagingSenderId: '878165496369',
    projectId: 'tasksheet-613',
    authDomain: 'tasksheet-613.firebaseapp.com',
    storageBucket: 'tasksheet-613.firebasestorage.app',
    measurementId: 'G-5BDQWZM3JS',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtLceb29RlMS349TkJeCeWkV26q3c9EoY',
    appId: '1:878165496369:ios:efdfed24e6874507a93b10',
    messagingSenderId: '878165496369',
    projectId: 'tasksheet-613',
    storageBucket: 'tasksheet-613.firebasestorage.app',
    iosBundleId: 'com.example.ts613Firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtLceb29RlMS349TkJeCeWkV26q3c9EoY',
    appId: '1:878165496369:ios:efdfed24e6874507a93b10',
    messagingSenderId: '878165496369',
    projectId: 'tasksheet-613',
    storageBucket: 'tasksheet-613.firebasestorage.app',
    iosBundleId: 'com.example.ts613Firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAjRW7nwHrTWGMipxWecjjNoeotUjayaE',
    appId: '1:878165496369:web:166b553d68f35e3fa93b10',
    messagingSenderId: '878165496369',
    projectId: 'tasksheet-613',
    authDomain: 'tasksheet-613.firebaseapp.com',
    storageBucket: 'tasksheet-613.firebasestorage.app',
    measurementId: 'G-2CMRKJW886',
  );
}
